(source "melpa" "http://melpa.org/packages/")
(source "melpa-stable" "http://stable.melpa.org/packages/")
(source gnu)
(source org)

(depends-on "chruby")
(depends-on "cider")
(depends-on "clojure-cheatsheet")
(depends-on "clojure-mode")
(depends-on "clojure-quick-repls")
(depends-on "color-theme-solarized")
(depends-on "deft")
(depends-on "evil")
(depends-on "evil-nerd-commenter")
(depends-on "evil-surround")
(depends-on "evil-visualstar")
(depends-on "flx-ido")
(depends-on "flycheck-clojure")
(depends-on "go-mode")
(depends-on "go-projectile")
(depends-on "ido-ubiquitous")
(depends-on "jsx-mode")
(depends-on "magit")
(depends-on "markdown-mode")
(depends-on "midje-mode")
(depends-on "multi-term")
(depends-on "multiple-cursors")
(depends-on "pallet")
(depends-on "php-mode")
(depends-on "popwin")
(depends-on "projectile")
(depends-on "projectile-rails")
(depends-on "rainbow-delimiters")
(depends-on "robe")
(depends-on "scss-mode")
(depends-on "smartparens")
(depends-on "yaml-mode")