(source "elpa" "http://elpa.gnu.org/packages/")
(source melpa)

(depends-on "cider")
(depends-on "clojure-cheatsheet")
(depends-on "clojure-mode")
(depends-on "clojure-quick-repls")
(depends-on "deft")
(depends-on "evil")
(depends-on "evil-surround")
(depends-on "evil-visualstar")
(depends-on "flycheck-clojure")
(depends-on "go-mode")
(depends-on "go-projectile")
(depends-on "ido-ubiquitous")
(depends-on "magit")
(depends-on "multi-term")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "projectile")
(depends-on "projectile-rails")